### ISSUE TITLE
Code splitting not working with Vue

### ISSUE THREAD

**Issue by securisec** [room-js/chrome-extension-ts-starter#2]
I really like your template, but have not used parcel before, so not really sure how to leverage it for code splitting. 

I am using both vuetify and lodash in my extension project, but the maps and final builds are quite large because parcel is not code splitting. 

My imports are pretty straight. `import { debounce } from 'lodash'` instead of importing all from lodash. 

Any ideas on this?

**Comment by yurist38** [comment]
To be honest, I have never configured code splitting in Parcel, but it supports it according to the [docs](https://parceljs.org/code_splitting.html). Can I ask you, why the bundle size is so important for you here? As I understand, the extension is loading from the user's file system. So he/she doesn't have to load it via web every time, just once when installing the extension. That's why I think that code splitting doesn't make any difference. Maybe I miss something?

**Comment by securisec** [comment]
you are right, code splitting may not necessarily make a difference in terms of load time, but it does make a difference in code quality and memory footprint. lodash is a great example of this. if i destruct one function from the import, it adding 700kb to the size also means it is loading that make functions.
